name: Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Extract version info
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"

          IS_PRERELEASE=false
          VERSION_TYPE=release

          if [[ "$TAG" =~ -rc[0-9]+$ ]]; then
            IS_PRERELEASE=true
            VERSION_TYPE=beta
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT

      - name: Publish with mc-publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: be-quiet-negotiator
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ github.ref_name }}
          github-draft: false
          github-prerelease: ${{ steps.version.outputs.is_prerelease }}
          name: Release ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          version-type: ${{ steps.version.outputs.version_type }}
          changelog-file: docs/changelog/v${{ steps.version.outputs.version }}.md
          files: |
            build/libs/be_quiet_negotiator-${{ steps.version.outputs.version }}.jar
            build/libs/be_quiet_negotiator-${{ steps.version.outputs.version }}-sources.jar
          loaders: |
            neoforge
          game-versions: |
            1.21.x