name: Release and Publish

on:
  push:
    tags:
      - 'v*'  # Match tags like v1.0.0 or v1.0.0-rc1

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Extract version info
        id: version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"

          IS_PRERELEASE=false
          CHANNEL="release"

          if [[ "$TAG" =~ -rc[0-9]+$ ]]; then
            IS_PRERELEASE=true
            CHANNEL="beta"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "channel=$CHANNEL" >> $GITHUB_OUTPUT

      - name: Read changelog
        id: changelog
        run: |
          FILE="docs/changelog/v${{ steps.version.outputs.version }}.md"
          if [ ! -f "$FILE" ]; then
            echo "Changelog not found: $FILE"
            exit 1
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat "$FILE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.version.outputs.is_prerelease }}
          files: |
            build/libs/*.jar

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: be-quiet-negotiator  # Replace with your Modrinth project ID
          name: Release ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          changelog: ${{ steps.changelog.outputs.changelog }}
          channel: ${{ steps.version.outputs.channel }}
          loaders: '["neoforge"]'
          game-versions: '["1.21.x"]'
          files: |
            build/libs/be_quite_negotiator-${{ steps.version.outputs.version }}.jar
            build/libs/be_quite_negotiator-${{ steps.version.outputs.version }}-sources.jar
          primary-file: be_quite_negotiator-${{ steps.version.outputs.version }}.jar
